################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CMakeFiles/3.17.1/CompilerIdC \
CMakeFiles/3.17.1/CompilerIdCXX \
build/CMakeFiles/3.16.4/CompilerIdC \
build/CMakeFiles/3.16.4/CompilerIdCXX \
build/CMakeFiles/3.18.4/CompilerIdC \
build/CMakeFiles/3.18.4/CompilerIdCXX \
build/CMakeFiles/sensor.elf.dir \
build/bootloader/CMakeFiles/3.18.4/CompilerIdC \
build/bootloader/CMakeFiles/3.18.4/CompilerIdCXX \
build/bootloader/CMakeFiles/bootloader.elf.dir \
build/bootloader/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src \
build/bootloader/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32 \
build/bootloader/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32 \
build/bootloader/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp32 \
build/bootloader/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src \
build/bootloader/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir \
build/bootloader/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32 \
build/bootloader/esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches \
build/bootloader/esp-idf/hal/CMakeFiles/__idf_hal.dir \
build/bootloader/esp-idf/log/CMakeFiles/__idf_log.dir \
build/bootloader/esp-idf/main/CMakeFiles/__idf_main.dir \
build/bootloader/esp-idf/micro-ecc/CMakeFiles/__idf_micro-ecc.dir \
build/bootloader/esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32 \
build/bootloader/esp-idf/soc/CMakeFiles/__idf_soc.dir \
build/bootloader/esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir/esp32 \
build/bootloader \
build \
build/esp-idf/ESP32-OTA-Webserver/CMakeFiles/__idf_ESP32-OTA-Webserver.dir \
build/esp-idf/ESP32-OTA-Webserver/CMakeFiles/__idf_ESP32-OTA-Webserver.dir/__/__ \
build/esp-idf/I2Cbus/CMakeFiles/__idf_I2Cbus.dir/src \
build/esp-idf/MPUdriver/CMakeFiles/__idf_MPUdriver.dir/src \
build/esp-idf/app_trace/CMakeFiles/__idf_app_trace.dir \
build/esp-idf/app_trace/CMakeFiles/__idf_app_trace.dir/gcov \
build/esp-idf/app_update/CMakeFiles/__idf_app_update.dir \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/cores/esp32 \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/BluetoothSerial/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/EEPROM/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/FFat/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/FS/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/Preferences/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/SPI/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/SPIFFS/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/Ticker/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/Update/src \
build/esp-idf/arduino-esp32/CMakeFiles/__idf_arduino-esp32.dir/libraries/Wire/src \
build/esp-idf/asio/CMakeFiles/__idf_asio.dir/asio/asio/src \
build/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src \
build/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/idf \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/common/btc/core \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/common/osi \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/controller \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/api \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/ar \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/av \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/dm \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/gatt \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/hf_ag \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/hf_client \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/hh \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/jv \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/sdp \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/bta/sys \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/core \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/esp/blufi \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/a2dp \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/avrc \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/gap \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/gatt \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/hf_ag \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/hf_client \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/hid \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/btc/profile/std/spp \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/device \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/external/sbc/decoder/srce \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/external/sbc/encoder/srce \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/external/sbc/plc \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/hci \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/main \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/a2dp \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/avct \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/avdt \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/avrc \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/btm \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/btu \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/gap \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/gatt \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/hcic \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/l2cap \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/rfcomm \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/sdp \
build/esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/smp \
build/esp-idf/cbor/CMakeFiles/__idf_cbor.dir/tinycbor/src \
build/esp-idf/cmock/CMakeFiles/__idf_cmock.dir/CMock/src \
build/esp-idf/coap/CMakeFiles/__idf_coap.dir/libcoap/src \
build/esp-idf/coap/CMakeFiles/__idf_coap.dir/port \
build/esp-idf/console/CMakeFiles/__idf_console.dir/argtable3 \
build/esp-idf/console/CMakeFiles/__idf_console.dir \
build/esp-idf/console/CMakeFiles/__idf_console.dir/linenoise \
build/esp-idf/cxx/CMakeFiles/__idf_cxx.dir \
build/esp-idf/driver/CMakeFiles/__idf_driver.dir \
build/esp-idf/driver/CMakeFiles/__idf_driver.dir/esp32 \
build/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32 \
build/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp32 \
build/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src \
build/esp-idf/esp-tls/CMakeFiles/__idf_esp-tls.dir/esp-tls-crypto \
build/esp-idf/esp-tls/CMakeFiles/__idf_esp-tls.dir \
build/esp-idf/esp32/CMakeFiles/__idf_esp32.dir \
build/esp-idf/esp_adc_cal/CMakeFiles/__idf_esp_adc_cal.dir \
build/esp-idf/esp_common/CMakeFiles/__idf_esp_common.dir/src \
build/esp-idf/esp_eth/CMakeFiles/__idf_esp_eth.dir/src \
build/esp-idf/esp_event/CMakeFiles/__idf_esp_event.dir \
build/esp-idf/esp_gdbstub/CMakeFiles/__idf_esp_gdbstub.dir/esp32 \
build/esp-idf/esp_gdbstub/CMakeFiles/__idf_esp_gdbstub.dir/src \
build/esp-idf/esp_gdbstub/CMakeFiles/__idf_esp_gdbstub.dir/xtensa \
build/esp-idf/esp_hid/CMakeFiles/__idf_esp_hid.dir/src \
build/esp-idf/esp_http_client/CMakeFiles/__idf_esp_http_client.dir \
build/esp-idf/esp_http_client/CMakeFiles/__idf_esp_http_client.dir/lib \
build/esp-idf/esp_http_server/CMakeFiles/__idf_esp_http_server.dir/src \
build/esp-idf/esp_http_server/CMakeFiles/__idf_esp_http_server.dir/src/util \
build/esp-idf/esp_https_ota/CMakeFiles/__idf_esp_https_ota.dir/src \
build/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir \
build/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32 \
build/esp-idf/esp_ipc/CMakeFiles/__idf_esp_ipc.dir \
build/esp-idf/esp_local_ctrl/CMakeFiles/__idf_esp_local_ctrl.dir/proto-c \
build/esp-idf/esp_local_ctrl/CMakeFiles/__idf_esp_local_ctrl.dir/src \
build/esp-idf/esp_netif/CMakeFiles/__idf_esp_netif.dir \
build/esp-idf/esp_netif/CMakeFiles/__idf_esp_netif.dir/loopback \
build/esp-idf/esp_netif/CMakeFiles/__idf_esp_netif.dir/lwip \
build/esp-idf/esp_pm/CMakeFiles/__idf_esp_pm.dir \
build/esp-idf/esp_ringbuf/CMakeFiles/__idf_esp_ringbuf.dir \
build/esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches \
build/esp-idf/esp_serial_slave_link/CMakeFiles/__idf_esp_serial_slave_link.dir \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/arch/xtensa \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/soc/esp32 \
build/esp-idf/esp_timer/CMakeFiles/__idf_esp_timer.dir/src \
build/esp-idf/esp_websocket_client/CMakeFiles/__idf_esp_websocket_client.dir \
build/esp-idf/esp_wifi/CMakeFiles/__idf_esp_wifi.dir/esp32 \
build/esp-idf/esp_wifi/CMakeFiles/__idf_esp_wifi.dir/src \
build/esp-idf/espcoredump/CMakeFiles/__idf_espcoredump.dir/src \
build/esp-idf/expat/CMakeFiles/__idf_expat.dir/expat/expat/lib \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/diskio \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/port/freertos \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/src \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/vfs \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/common \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/ascii \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/functions \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/rtu \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/tcp \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/port \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/serial_master/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/serial_slave/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_master/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_master/port \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_slave/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_slave/port \
build/esp-idf/freertos/CMakeFiles/__idf_freertos.dir \
build/esp-idf/freertos/CMakeFiles/__idf_freertos.dir/port \
build/esp-idf/freertos/CMakeFiles/__idf_freertos.dir/port/xtensa \
build/esp-idf/hal/CMakeFiles/__idf_hal.dir \
build/esp-idf/hal/CMakeFiles/__idf_hal.dir/esp32 \
build/esp-idf/heap/CMakeFiles/__idf_heap.dir \
build/esp-idf/jsmn/CMakeFiles/__idf_jsmn.dir/src \
build/esp-idf/json/CMakeFiles/__idf_json.dir/cJSON \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_box \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_box/curve25519xchacha20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/hchacha20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/salsa/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_generichash/blake2b \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_generichash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha256/cp \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha512/cp \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha512 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_kdf/blake2b \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_kdf \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_kx \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth/poly1305/sse2 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sse \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519/donna_c64 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretbox \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretbox/xchacha20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_shorthash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_sign \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_sign/ed25519 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/aes128ctr/nacl \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/aes128ctr \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/chacha20/dolbeau \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/chacha20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20/xmm6 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20/xmm6int \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa2012/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa2012 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa208/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa208 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/xchacha20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_verify/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/randombytes/nativeclient \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/randombytes \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/randombytes/salsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/randombytes/sysrandom \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/port \
build/esp-idf/log/CMakeFiles/__idf_log.dir \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/apps/dhcpserver \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/apps/ping \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/apps/sntp \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/api \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/apps/netbiosns \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/apps/sntp \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/core \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/core/ipv4 \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/core/ipv6 \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/netif \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/netif/ppp \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/debug \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/freertos \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/hooks \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/netif \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32 \
build/esp-idf/main/CMakeFiles/__idf_main.dir \
build/esp-idf/main/CMakeFiles/__idf_main.dir/__/__ \
build/esp-idf/mbedtls/CMakeFiles/__idf_mbedtls.dir/__/__ \
build/esp-idf/mbedtls/CMakeFiles/__idf_mbedtls.dir/esp_crt_bundle \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes/block \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/esp32 \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/parallel_engine \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir/__/__/port \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedx509.dir \
build/esp-idf/mdns/CMakeFiles/__idf_mdns.dir \
build/esp-idf/mqtt/CMakeFiles/__idf_mqtt.dir/esp-mqtt/lib \
build/esp-idf/mqtt/CMakeFiles/__idf_mqtt.dir/esp-mqtt \
build/esp-idf/newlib/CMakeFiles/__idf_newlib.dir \
build/esp-idf/newlib/CMakeFiles/__idf_newlib.dir/port \
build/esp-idf/nghttp/CMakeFiles/__idf_nghttp.dir/nghttp2/lib \
build/esp-idf/nghttp/CMakeFiles/__idf_nghttp.dir/port \
build/esp-idf/nvs_flash/CMakeFiles/__idf_nvs_flash.dir/src \
build/esp-idf/openssl/CMakeFiles/__idf_openssl.dir/library \
build/esp-idf/openssl/CMakeFiles/__idf_openssl.dir/platform \
build/esp-idf/perfmon/CMakeFiles/__idf_perfmon.dir \
build/esp-idf/protobuf-c/CMakeFiles/__idf_protobuf-c.dir/protobuf-c/protobuf-c \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/common \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/security \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/simple_ble \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/transports \
build/esp-idf/pthread/CMakeFiles/__idf_pthread.dir \
build/esp-idf/sdmmc/CMakeFiles/__idf_sdmmc.dir \
build/esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32 \
build/esp-idf/soc/CMakeFiles/__idf_soc.dir \
build/esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir \
build/esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir/esp32 \
build/esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir \
build/esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/spiffs/src \
build/esp-idf/tcp_transport/CMakeFiles/__idf_tcp_transport.dir \
build/esp-idf/tcpip_adapter/CMakeFiles/__idf_tcpip_adapter.dir \
build/esp-idf/ucglib/CMakeFiles/__idf_ucglib.dir/cppsrc \
build/esp-idf/ucglib/CMakeFiles/__idf_ucglib.dir/csrc \
build/esp-idf/ulp/CMakeFiles/__idf_ulp.dir \
build/esp-idf/unity/CMakeFiles/__idf_unity.dir/unity/src \
build/esp-idf/unity/CMakeFiles/__idf_unity.dir \
build/esp-idf/vfs/CMakeFiles/__idf_vfs.dir \
build/esp-idf/wear_levelling/CMakeFiles/__idf_wear_levelling.dir \
build/esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/proto-c \
build/esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/port \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/ap \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/common \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/crypto \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/eap_peer \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/esp_supplicant \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/rsn_supp \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/utils \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/wps \
build/esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir \
build/esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/esp32 \
components/ESP32-OTA-Webserver \
components/I2Cbus/examples/main \
components/I2Cbus/src \
components/MPUdriver/examples/mpu_i2c/main \
components/MPUdriver/examples/mpu_real/main \
components/MPUdriver/examples/mpu_spi/main \
components/MPUdriver/src \
components/MPUdriver/test/mpu-tests \
components/MPUdriver/test/unit-test-app/main \
components/arduino-esp32/cores/esp32 \
components/arduino-esp32/cores/esp32/libb64 \
components/arduino-esp32/libraries/BluetoothSerial/src \
components/arduino-esp32/libraries/EEPROM/src \
components/arduino-esp32/libraries/ESP32/examples/Camera/CameraWebServer \
components/arduino-esp32/libraries/FFat/src \
components/arduino-esp32/libraries/FS/src \
components/arduino-esp32/libraries/Preferences/src \
components/arduino-esp32/libraries/SPI/src \
components/arduino-esp32/libraries/SPIFFS/src \
components/arduino-esp32/libraries/Ticker/src \
components/arduino-esp32/libraries/Update/src \
components/arduino-esp32/libraries/Wire/src \
components/patches/drivers \
components/ucglib/cppsrc \
components/ucglib/cppsrc_sdspi \
components/ucglib/csrc \
components/ucglib/sys/sdl/dev \
components/ucglib/sys/sdl/show_tga \
components/ucglib/sys/sdl/test \
components/ucglib/sys/sdl/test_disk \
components/ucglib/sys/sdl/test_font \
components/ucglib/sys/sdl/test_font_rotate \
components/ucglib/sys/sdl/test_rotate \
components/ucglib/sys/sdl/test_scale \
components/ucglib/sys/sdl/ucglib_logo \
components/ucglib/sys/stdout/com \
components/ucglib/sys/tga/dev \
components/ucglib/sys/tga/examples \
components/ucglib/sys/tga/font_array \
components/ucglib/sys/tga/font_overview \
components/ucglib/sys/tga/test \
components/ucglib/tools/font/bdf2ucg \
components/ucglib/tools/font/bdf2ucg_obsolete \
components/ucglib/tools/font/bdfconv \
components/ucglib/tools/font/otf2bdf \
components/ucglib/tools/linear \
main \
main/build/CMakeFiles/3.18.4/CompilerIdC \
main/build/CMakeFiles/3.18.4/CompilerIdCXX \
main/esp-idf/components/driver \
wav2head \

