name: CMake

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Build 
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      # working-directory: ~/BtBridge
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      
      run:  touch $PWD/main/Version.h;
            docker run --rm -v $PWD:/project -w /project espressif/idf:release-v4.3 idf.py build;
            VER=`date +"%y.%m%d-%H%M"`;
            cp $PWD/build/btbridge.bin $PWD/images/btbridge-${VER}.bin;
            git config user.name github-actions;
            git config user.email github-actions@github.com;
            git add $PWD/images/btbridge-${VER}.bin;
            git commit -a -m "new version build btbridge-${VER}.bin";
            git push;

  
      
